# Generated by Django 5.1.3 on 2024-12-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='Amateur', max_length=10),
        ),
    ]
