# Generated by Django 5.1.3 on 2024-12-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth1', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
