# Generated by Django 5.1.3 on 2024-12-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth1', '0004_remove_user_age_remove_user_type_user_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default='nan', max_length=100),
        ),
    ]
