# Generated by Django 5.1.3 on 2024-12-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth1', '0005_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
