# Generated by Django 5.1.3 on 2024-12-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth1', '0006_alter_user_fullname_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
