# Generated by Django 5.1.3 on 2024-12-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth1', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isVerfied',
            field=models.BooleanField(default=False),
        ),
    ]
