# Generated by Django 5.1.3 on 2024-12-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth1', '0008_user_isverfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isVerfied',
            new_name='isVerified',
        ),
    ]
