# Generated by Django 5.1.3 on 2024-12-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth1', '0009_rename_isverfied_user_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
