# Generated by Django 5.1.3 on 2024-12-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth1', '0010_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
